# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_tb_secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_key', models.CharField(max_length=20)),
                ('tb_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='t_tb_shopcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(max_length=50)),
                ('categorylist', models.CharField(max_length=100)),
                ('categoryurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_tb_shoplist',
            fields=[
                ('shopid', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='t_wx_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_msg_type', models.CharField(max_length=20)),
                ('wx_msg_value', models.CharField(max_length=200)),
            ],
        ),
    ]
