# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_wx_secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_appid', models.CharField(default=True, max_length=20)),
                ('wx_secret', models.CharField(default=True, max_length=200)),
                ('wx_token', models.CharField(default=True, max_length=100)),
            ],
        ),
    ]
