# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0002_t_wx_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_wx_secret',
            name='wx_appname',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
