# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0003_t_wx_secret_wx_appname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_tb_secret',
            name='tb_key',
        ),
        migrations.RemoveField(
            model_name='t_tb_secret',
            name='tb_value',
        ),
        migrations.AddField(
            model_name='t_tb_secret',
            name='wx_appid',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='t_tb_secret',
            name='wx_appname',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='t_tb_secret',
            name='wx_secret',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='t_tb_secret',
            name='wx_token',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
