# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0004_auto_20181113_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_wx_msg',
            name='wx_msg_keyword',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
