# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0006_auto_20181113_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_type',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_value',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
