# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-20 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0007_auto_20181113_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_tb_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.CharField(max_length=50, null=True)),
                ('commodity_name', models.CharField(max_length=200, null=True)),
                ('shop_master_map_url', models.CharField(max_length=200, null=True)),
                ('shop_detail_url', models.CharField(max_length=200, null=True)),
                ('shop_category', models.CharField(max_length=100, null=True)),
                ('shop_tbk_url', models.CharField(max_length=500, null=True)),
                ('shop_price', models.CharField(max_length=50, null=True)),
                ('shop_volume', models.CharField(max_length=50, null=True)),
                ('shop_income_ratio', models.CharField(max_length=50, null=True)),
                ('shop_commission', models.CharField(max_length=50, null=True)),
                ('shop_seller_ww', models.CharField(max_length=50, null=True)),
                ('shop_seller_id', models.CharField(max_length=50, null=True)),
                ('shop_name', models.CharField(max_length=100, null=True)),
                ('platform_type', models.CharField(max_length=50, null=True)),
                ('coupon_id', models.CharField(max_length=100, null=True)),
                ('coupon_count', models.CharField(max_length=50, null=True)),
                ('coupon_surplus', models.CharField(max_length=50, null=True)),
                ('coupon_denomination', models.CharField(max_length=50, null=True)),
                ('coupon_start_time', models.CharField(max_length=50, null=True)),
                ('coupon_end_time', models.CharField(max_length=50, null=True)),
                ('coupon_url', models.CharField(max_length=500, null=True)),
                ('coupon_extension', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_appid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_appname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_secret',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_keyword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_appid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_appname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_secret',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
