# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-13 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0007_auto_20181113_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_appid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_appname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_secret',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_tb_secret',
            name='tb_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_keyword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_msg',
            name='wx_msg_value',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_appid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_appname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_secret',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_wx_secret',
            name='wx_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
