# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-20 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0008_auto_20181120_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_tb_shop',
            name='commodity_id',
        ),
    ]
