# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0009_remove_t_tb_shop_commodity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_tb_shop',
            name='commodity_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
