# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0013_auto_20181120_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_tb_shop',
            name='pw_conversion',
            field=models.CharField(max_length=50, null=True, verbose_name='口令'),
        ),
    ]
