# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat_conpon', '0015_auto_20181120_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
